name: catbiblio_app
description: "Aplicación Móvil para el Catálogo Bibliotecario de la Universidad Veracruzana"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.3.2
  xml: ^6.6.1
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.9.0
  dio_smart_retry: ^7.0.1
  provider: ^6.1.5
  readmore: ^3.0.0
  flutter_dotenv: ^6.0.0
  skeletonizer: ^2.1.0+1
  flutter_launcher_icons: ^0.14.4
  go_router: ^17.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env
  fonts:
  - family: Roboto Mono
    fonts:
      - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
      - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter_24pt-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter_24pt-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter_24pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Inter_24pt-Black.ttf
        weight: 900
